//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Equipo.java
//  @ Date : 19/07/2022
//  @ Author : 
//
//




public class Equipo {
	private String nombre;
	private int lugar;
	private int tirosEsquina;
	private int goles;
	private int ganados;
	private int perdidos;
	private int tirosAgol;
	private int amarillas;
	private int rojas;
	private int faltas;
	public Equipo() {
		nombre = "";
		lugar = 0;
		tirosEsquina = 0;
		goles = 0;
		ganados = 0;
		perdidos  = 0;
		tirosAgol  = 0;
		amarillas = 0;
		rojas = 0;
		faltas = 0;
	}
	
	public void setNombre(String newNombre) {
	}
	
	public String getNombre() {
		return nombre;
	}
	
	public void setLugar(int newlugar) {
	}
	
	public int getLugar() {
	}
	
	public void setTirosEsquina(int newtirosEsquina) {
	}
	
	public int getTirosEsquina() {
	}
	
	public void setGoles(int newgoles) {
	}
	
	public int getGoles() {
	}
	
	public void setGanados(int newganados) {
	}
	
	public int getGanados() {
	}
	
	public void setPerdidos(int newperdidos) {
	}
	
	public int getPerdidos() {
	}
	
	public void setTirosAgol(int newtirosAgol) {
	}
	
	public int getTirosAgol() {
	}
	
	public void setAmarillas(int newamarillas) {
	}
	
	public int getAmarillas() {
	}
	
	public void setRojas(int newrojas) {
	}
	
	public int getRojas() {
	}
	
	public void setFaltas(int newfaltas) {
	}
	
	public int getFaltas() {
	}
	
	public String toString() {
	}
}
