//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Principal.java
//  @ Date : 19/07/2022
//  @ Author : 
//
//




public class Principal {
	public static void main(String[] args) {
	}
}
