//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Torneo.java
//  @ Date : 19/07/2022
//  @ Author : 
//
//




public class Torneo {
	private Equipo equipo1;
	private Equipo equipo2;
	private Equipo equipo3;
	private Equipo equipo4;
	private Equipo equipo5;
	public Torneo() {
	}
	
	public int cantTotalGoles() {
	}
	
	public int cantTotalTirosEsquina() {
	}
	
	public int cantTotalAmarillas() {
	}
	
	public int cantTotalRojas() {
	}
	
	public void llenarEquipo(int i, String nombre, int lugar, int tirosEsq, int goles, int ganados, int perdidos, int tirosGol, int amarillas, int rojas, int faltas) {
	}
	
	public String toString() {
	}
}
